### ISSUE TITLE
Error on scraping

### ISSUE THREAD

**Issue by TheFantasticLoki** [host505/plugin.video.theoath#25]
Happens when trying to scrape links on the movie 2 Fast 2 Furious and some other movies in the franchise. Here is the error from the log.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                                   Error Contents: Expecting ',' delimiter or '}': line 1 column 254 (char 253)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\plugin.video.theoath\theoath.py", line 421, in <module>
                                                       sources.sources().addItem(title)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\plugin.video.theoath\resources\lib\modules\sources.py", line 114, in addItem
                                                       meta = json.loads(meta)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 370, in decode
                                                       obj, end = self.raw_decode(s)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 400, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\scanner.py", line 79, in scan_once
                                                       return _scan_once(string, idx)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\scanner.py", line 44, in _scan_once
                                                       return parse_object((string, idx + 1), encoding, strict,
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 209, in JSONObject
                                                       raise JSONDecodeError("Expecting ',' delimiter or '}'", s, end - 1)
                                                   simplejson.errors.JSONDecodeError: Expecting ',' delimiter or '}': line 1 column 254 (char 253)
                                                   -->End of Python script error report<--

**Comment by host505** [comment]
I tried the titles you mentioned and couldn't reproduce your issue.
What is your metadata language (Info language add-on setting)? If auto, what's your Kodi language setting?
I'll have a closer look, probably over the weekend.

**Comment by TheFantasticLoki** [comment]
Maybe if I just post my Kodi.log you could get more info from that since there are a lot of errors and weird warnings but I just started using kodi again so I don't know how to fix them all. Just a standard Diggzrepo Chef Wizard install with Netflix addon added but still had issues before that.
[kodi.log](https://github.com/host505/plugin.video.theoath/files/6592006/kodi.log)
